name: Diagram

on:
  push:
    branches: ['main']
  workflow_dispatch:
  
jobs:
  get_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: "docs,tests,.github,.gitignore,.env_example,.readthedocs.yaml,tox.ini,ecosystem.json,architecture.png"
          branch: repo-visualizer-diagram
